# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\code\python\rename\View\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.setupUi(self)
        self.retranslateUi(self)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.set_format_frame = QtWidgets.QFrame(self.centralwidget)
        self.set_format_frame.setGeometry(QtCore.QRect(10, 40, 521, 481))
        self.set_format_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.set_format_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.set_format_frame.setObjectName("set_format_frame")
        self.tabl_frame = QtWidgets.QFrame(self.set_format_frame)
        self.tabl_frame.setGeometry(QtCore.QRect(70, 10, 381, 61))
        self.tabl_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tabl_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tabl_frame.setObjectName("tabl_frame")
        self.label_2 = QtWidgets.QLabel(self.tabl_frame)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 71, 61))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.tb_box = QtWidgets.QComboBox(self.tabl_frame)
        self.tb_box.setGeometry(QtCore.QRect(90, 10, 191, 41))
        self.tb_box.setObjectName("tb_box")
        self.add_table_btn = QtWidgets.QPushButton(self.tabl_frame)
        self.add_table_btn.setGeometry(QtCore.QRect(290, 10, 81, 41))
        self.add_table_btn.setObjectName("add_table_btn")
        self.frame_4 = QtWidgets.QFrame(self.set_format_frame)
        self.frame_4.setGeometry(QtCore.QRect(20, 80, 491, 391))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.tab_tags_frame = QtWidgets.QFrame(self.frame_4)
        self.tab_tags_frame.setGeometry(QtCore.QRect(10, 90, 481, 71))
        self.tab_tags_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tab_tags_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tab_tags_frame.setObjectName("tab_tags_frame")
        self.label_3 = QtWidgets.QLabel(self.tab_tags_frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 72, 51))
        self.label_3.setObjectName("label_3")
        self.tb_tags_listVeiw = QtWidgets.QListView(self.tab_tags_frame)
        self.tb_tags_listVeiw.setGeometry(QtCore.QRect(90, 10, 381, 51))
        self.tb_tags_listVeiw.setObjectName("tb_tags_listVeiw")
        self.tags_frame = QtWidgets.QFrame(self.frame_4)
        self.tags_frame.setGeometry(QtCore.QRect(10, 170, 481, 71))
        self.tags_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tags_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tags_frame.setObjectName("tags_frame")
        self.label_4 = QtWidgets.QLabel(self.tags_frame)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 72, 51))
        self.label_4.setObjectName("label_4")
        self.tags_listVeiw = QtWidgets.QListView(self.tags_frame)
        self.tags_listVeiw.setGeometry(QtCore.QRect(90, 10, 381, 51))
        self.tags_listVeiw.setObjectName("tags_listVeiw")
        self.format_frame = QtWidgets.QFrame(self.frame_4)
        self.format_frame.setGeometry(QtCore.QRect(10, 250, 481, 71))
        self.format_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.format_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.format_frame.setObjectName("format_frame")
        self.label_5 = QtWidgets.QLabel(self.format_frame)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 72, 51))
        self.label_5.setObjectName("label_5")
        self.format_listVeiw = QtWidgets.QListView(self.format_frame)
        self.format_listVeiw.setGeometry(QtCore.QRect(90, 10, 381, 51))
        self.format_listVeiw.setObjectName("format_listVeiw")
        self.add_format_btn = QtWidgets.QPushButton(self.frame_4)
        self.add_format_btn.setGeometry(QtCore.QRect(180, 330, 131, 51))
        self.add_format_btn.setObjectName("add_format_btn")
        self.keys_frame = QtWidgets.QFrame(self.frame_4)
        self.keys_frame.setGeometry(QtCore.QRect(10, 10, 481, 71))
        self.keys_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keys_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keys_frame.setObjectName("keys_frame")
        self.label_7 = QtWidgets.QLabel(self.keys_frame)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 72, 51))
        self.label_7.setObjectName("label_7")
        self.tb_tags_listVeiw_2 = QtWidgets.QListView(self.keys_frame)
        self.tb_tags_listVeiw_2.setGeometry(QtCore.QRect(90, 10, 381, 51))
        self.tb_tags_listVeiw_2.setObjectName("tb_tags_listVeiw_2")
        self.rename_frame = QtWidgets.QFrame(self.centralwidget)
        self.rename_frame.setGeometry(QtCore.QRect(550, 40, 341, 481))
        self.rename_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rename_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rename_frame.setObjectName("rename_frame")
        self.format_choice_frame = QtWidgets.QFrame(self.rename_frame)
        self.format_choice_frame.setGeometry(QtCore.QRect(10, 10, 321, 61))
        self.format_choice_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.format_choice_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.format_choice_frame.setObjectName("format_choice_frame")
        self.label_6 = QtWidgets.QLabel(self.format_choice_frame)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 71, 61))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.format_choice_box = QtWidgets.QComboBox(self.format_choice_frame)
        self.format_choice_box.setGeometry(QtCore.QRect(90, 10, 211, 41))
        self.format_choice_box.setObjectName("format_choice_box")
        self.file_addRR_frame = QtWidgets.QFrame(self.rename_frame)
        self.file_addRR_frame.setGeometry(QtCore.QRect(10, 80, 321, 391))
        self.file_addRR_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.file_addRR_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.file_addRR_frame.setObjectName("file_addRR_frame")
        self.label = QtWidgets.QLabel(self.file_addRR_frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 72, 15))
        self.label.setObjectName("label")
        self.file_treeView = QtWidgets.QTreeView(self.file_addRR_frame)
        self.file_treeView.setGeometry(QtCore.QRect(0, 20, 311, 301))
        self.file_treeView.setObjectName("file_treeView")
        self.start_btn = QtWidgets.QPushButton(self.file_addRR_frame)
        self.start_btn.setGeometry(QtCore.QRect(100, 330, 121, 51))
        self.start_btn.setObjectName("start_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "表格选择:"))
        self.add_table_btn.setText(_translate("MainWindow", "添加表格"))
        self.label_3.setText(_translate("MainWindow", "表格标签："))
        self.label_4.setText(_translate("MainWindow", "普通标签："))
        self.label_5.setText(_translate("MainWindow", "名称格式："))
        self.add_format_btn.setText(_translate("MainWindow", "确定"))
        self.label_7.setText(_translate("MainWindow", " 主  键："))
        self.label_6.setText(_translate("MainWindow", "格式选择:"))
        self.label.setText(_translate("MainWindow", "文件导入"))
        self.start_btn.setText(_translate("MainWindow", "开始"))

